name: Deploy tardis-setups documentation

on: 
  push:
  

jobs:

  build:
    name: Build docs
    runs-on: ubuntu-latest
    
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v2
      - run: pwd
      - run: |
          cd ..
          pwd
          ls
