name: Deploy tardis-setups documentation

on: 
  push:
  

jobs:

  build:
    name: Build docs
    runs-on: ubuntu-latest
    
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: tardis-sn/tardis

      - run: |
          pwd
          ls